language: node_js
node_js:
  - "0.12"
  - "io.js"
branches:
  only:
    - master
sudo: false
script: "gulp coverage"
after_success:
  - npm install -g codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=4ee6d5da5ef16374c4007cfbfceada7477e3085739db13454a67a7d96dc89764 codeclimate-test-reporter < coverage/lcov.info