language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"
branches:
  only:
    - master
sudo: false
script: "npm run test"
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
